head = [["Laser Eyes"],
        ["Large Brain"],
        ["Demon Horns"],
        ["Invisible"],
        ["Rebel Pilot"],
        ["Top Hat"],
        ["Gills"],
        ["Snout"],
        ["No Teeth"],
        ["Deaf"],
        ["Can’t smell"],
        ["Blind"]]

body = [["Demon Wings"],
        ["Rebel Pilot Armor"],
        ["Extra Legs"],
        ["Scuba Tank"],
        ["Invisible"],
        ["Camouflage"],
        ["Porcupine Quills"],
        ["Normal"]]

legs = [["Invisible"],
        ["Shotgun"],
        ["Crab Claws"],
        ["Hooks"],
        ["Flippers"],
        ["Thumbs"],
        ["Claws"],
        ["Normal"],
        ["No Claws"]]
